// dummy data for noida civic complaint system
import { Report, CategoryStats, TrendData, DepartmentWorkload } from './definitions';

export const dummyReports: Report[] = [
  // cluster 1: electrical issues in sector 62
  {
    id: 'REP-001',
    title: 'Streetlight flickering near main road',
    category: 'Streetlight Out',
    description: 'The streetlight at the corner of the C-block market has been flickering for 3 days.',
    location: { lat: 28.6278, lng: 77.3724 },
    address: 'Near C-Block Market, Sector 62, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ff6b6b/ffffff?text=Streetlight+Issue',
    status: 'New',
    createdAt: '2025-01-15T10:00:00Z',
    upvotes: 5,
    priority: 4,
    assignedTo: 'Electrical',
  },
  {
    id: 'REP-002',
    title: 'Exposed wiring from pole',
    category: 'Electrical Hazard',
    description: 'A junction box on an electricity pole is open with wires hanging out. Very dangerous.',
    location: { lat: 28.6285, lng: 77.3719 },
    address: 'Opposite TCS Building, Sector 62, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ff4757/ffffff?text=Electrical+Hazard',
    status: 'Acknowledged',
    createdAt: '2025-01-14T14:30:00Z',
    upvotes: 8,
    priority: 5,
    assignedTo: 'Electrical',
  },
  {
    id: 'REP-003',
    title: 'Street light completely out',
    category: 'Streetlight Out',
    description: 'No lighting on the entire stretch near sector 62 metro station.',
    location: { lat: 28.6280, lng: 77.3720 },
    address: 'Near Sector 62 Metro Station, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ff6b6b/ffffff?text=Dark+Street',
    status: 'New',
    createdAt: '2025-01-15T08:45:00Z',
    upvotes: 12,
    priority: 4,
    assignedTo: 'Electrical',
  },
  
  // cluster 2: potholes in sector 18
  {
    id: 'REP-004',
    title: 'Large pothole causing traffic jams',
    category: 'Pothole',
    description: 'A very deep pothole right after the Wave Mall exit is a major hazard.',
    location: { lat: 28.5706, lng: 77.3253 },
    address: 'Near Wave Mall, Sector 18, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/8b4513/ffffff?text=Deep+Pothole',
    status: 'In Progress',
    createdAt: '2025-01-12T09:15:00Z',
    upvotes: 15,
    priority: 5,
    assignedTo: 'Public Works',
  },
  {
    id: 'REP-005',
    title: 'Same pothole getting worse',
    category: 'Pothole',
    description: 'Another report for the pothole near Wave Mall. It is getting worse.',
    location: { lat: 28.5707, lng: 77.3254 }, // slightly diff coords for clustering test
    address: 'Exit road of Wave Mall, Sector 18, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/8b4513/ffffff?text=Pothole+Worsened',
    status: 'New',
    createdAt: '2025-01-15T11:00:00Z',
    upvotes: 3,
    priority: 5,
    assignedTo: 'Public Works',
  },
  {
    id: 'REP-006',
    title: 'Multiple potholes on service lane',
    category: 'Pothole',
    description: 'Service lane near Wave Mall has 3-4 potholes making it undrivable.',
    location: { lat: 28.5708, lng: 77.3255 },
    address: 'Service Lane, Wave Mall, Sector 18, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/8b4513/ffffff?text=Multiple+Potholes',
    status: 'New',
    createdAt: '2025-01-15T16:20:00Z',
    upvotes: 7,
    priority: 4,
    assignedTo: 'Public Works',
  },

  // waste mgmt issues
  {
    id: 'REP-007',
    title: 'Garbage overflowing near pari chowk',
    category: 'Waste Management',
    description: 'The community bin near Pari Chowk has not been cleared for a week.',
    location: { lat: 28.4682, lng: 77.5090 },
    address: 'Near Pari Chowk, Greater Noida',
    imageUrl: 'https://via.placeholder.com/300x200/228b22/ffffff?text=Overflowing+Bin',
    status: 'Resolved',
    createdAt: '2025-01-08T12:00:00Z',
    resolvedAt: '2025-01-10T10:30:00Z',
    upvotes: 3,
    priority: 3,
    assignedTo: 'Sanitation',
  },
  {
    id: 'REP-008',
    title: 'Stray dogs near garbage dump',
    category: 'Waste Management',
    description: 'Uncollected garbage attracting stray dogs in residential area.',
    location: { lat: 28.5355, lng: 77.3910 },
    address: 'Sector 50, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/228b22/ffffff?text=Stray+Dogs',
    status: 'Acknowledged',
    createdAt: '2025-01-13T07:30:00Z',
    upvotes: 9,
    priority: 4,
    assignedTo: 'Sanitation',
  },

  // water logging issues
  {
    id: 'REP-009',
    title: 'Water logging after rain',
    category: 'Water Logging',
    description: 'Underpass gets completely flooded during monsoon.',
    location: { lat: 28.5678, lng: 77.3456 },
    address: 'Sector 15 Underpass, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/4682b4/ffffff?text=Flooded+Road',
    status: 'In Progress',
    createdAt: '2025-01-11T14:15:00Z',
    upvotes: 22,
    priority: 5,
    assignedTo: 'Water Board',
  },
  {
    id: 'REP-010',
    title: 'Broken drainage cover',
    category: 'Water Logging',
    description: 'Manhole cover missing causing water stagnation.',
    location: { lat: 28.5234, lng: 77.3567 },
    address: 'Sector 37, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/4682b4/ffffff?text=Broken+Drain',
    status: 'New',
    createdAt: '2025-01-14T09:45:00Z',
    upvotes: 6,
    priority: 4,
    assignedTo: 'Public Works',
  },

  // signage issues
  {
    id: 'REP-011',
    title: 'Traffic sign fallen down',
    category: 'Broken Signage',
    description: 'Important speed limit sign has fallen and blocking footpath.',
    location: { lat: 28.5890, lng: 77.3234 },
    address: 'Near DLF Mall, Sector 18, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ffa500/ffffff?text=Fallen+Sign',
    status: 'New',
    createdAt: '2025-01-15T13:20:00Z',
    upvotes: 4,
    priority: 3,
    assignedTo: 'Traffic',
  },
  {
    id: 'REP-012',
    title: 'Faded road markings',
    category: 'Broken Signage',
    description: 'Zebra crossing completely faded, dangerous for pedestrians.',
    location: { lat: 28.6123, lng: 77.3890 },
    address: 'Sector 76, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ffa500/ffffff?text=Faded+Crossing',
    status: 'Acknowledged',
    createdAt: '2025-01-13T11:10:00Z',
    upvotes: 8,
    priority: 4,
    assignedTo: 'Traffic',
  },

  // more electrical issues for clustering
  {
    id: 'REP-013',
    title: 'Transformer making loud noise',
    category: 'Electrical Hazard',
    description: 'Local transformer making concerning buzzing sounds.',
    location: { lat: 28.6290, lng: 77.3715 }, // close to sector 62 cluster
    address: 'Near Fortis Hospital, Sector 62, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ff4757/ffffff?text=Noisy+Transformer',
    status: 'New',
    createdAt: '2025-01-15T15:30:00Z',
    upvotes: 11,
    priority: 5,
    assignedTo: 'Electrical',
  },
  {
    id: 'REP-014',
    title: 'Power cable hanging low',
    category: 'Electrical Hazard',
    description: 'High voltage cable hanging dangerously low over road.',
    location: { lat: 28.6275, lng: 77.3722 },
    address: 'B-Block, Sector 62, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/ff4757/ffffff?text=Low+Cable',
    status: 'New',
    createdAt: '2025-01-15T12:45:00Z',
    upvotes: 16,
    priority: 5,
    assignedTo: 'Electrical',
  },

  // resolved issues for analytics
  {
    id: 'REP-015',
    title: 'Fixed streetlight',
    category: 'Streetlight Out',
    description: 'This was resolved quickly.',
    location: { lat: 28.5456, lng: 77.3123 },
    address: 'Sector 25, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/32cd32/ffffff?text=Fixed+Light',
    status: 'Resolved',
    createdAt: '2025-01-10T10:00:00Z',
    resolvedAt: '2025-01-12T14:30:00Z',
    upvotes: 2,
    priority: 2,
    assignedTo: 'Electrical',
  },
  {
    id: 'REP-016',
    title: 'Cleaned garbage area',
    category: 'Waste Management',
    description: 'Garbage collection improved.',
    location: { lat: 28.5234, lng: 77.3456 },
    address: 'Sector 45, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/32cd32/ffffff?text=Clean+Area',
    status: 'Resolved',
    createdAt: '2025-01-09T08:00:00Z',
    resolvedAt: '2025-01-11T16:00:00Z',
    upvotes: 5,
    priority: 3,
    assignedTo: 'Sanitation',
  },
  {
    id: 'REP-017',
    title: 'Repaired pothole',
    category: 'Pothole',
    description: 'Road surface fixed.',
    location: { lat: 28.5567, lng: 77.3234 },
    address: 'Sector 35, Noida',
    imageUrl: 'https://via.placeholder.com/300x200/32cd32/ffffff?text=Fixed+Road',
    status: 'Resolved',
    createdAt: '2025-01-08T14:20:00Z',
    resolvedAt: '2025-01-13T11:45:00Z',
    upvotes: 7,
    priority: 4,
    assignedTo: 'Public Works',
  }
];

// analytics dummy data
export const categoryStats: CategoryStats[] = [
  { category: 'Pothole', count: 8, resolved: 2 },
  { category: 'Streetlight Out', count: 6, resolved: 1 },
  { category: 'Electrical Hazard', count: 5, resolved: 0 },
  { category: 'Waste Management', count: 4, resolved: 2 },
  { category: 'Water Logging', count: 3, resolved: 0 },
  { category: 'Broken Signage', count: 2, resolved: 0 },
];

export const trendData: TrendData[] = [
  { date: '2025-01-08', count: 3 },
  { date: '2025-01-09', count: 1 },
  { date: '2025-01-10', count: 2 },
  { date: '2025-01-11', count: 1 },
  { date: '2025-01-12', count: 2 },
  { date: '2025-01-13', count: 3 },
  { date: '2025-01-14', count: 4 },
  { date: '2025-01-15', count: 8 },
];

export const departmentWorkload: DepartmentWorkload[] = [
  { department: 'Electrical', openIssues: 8, avgResolutionTime: 3.2 },
  { department: 'Public Works', openIssues: 6, avgResolutionTime: 5.1 },
  { department: 'Sanitation', openIssues: 2, avgResolutionTime: 2.8 },
  { department: 'Traffic', openIssues: 2, avgResolutionTime: 4.5 },
  { department: 'Water Board', openIssues: 1, avgResolutionTime: 7.2 },
];
